// <auto-generated />
using System;
using HotelManagePro.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagePro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241218104146_Testing PK name change")]
    partial class TestingPKnamechange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagePro.Features.Booking.Models.Bookings", b =>
                {
                    b.Property<int>("BookingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingsId"));

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<int?>("CustomersId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<int>("InvoicesId")
                        .HasColumnType("int");

                    b.HasKey("BookingsId");

                    b.HasIndex("CustomersId");

                    b.HasIndex("InvoicesId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelManagePro.Features.Customer.Models.Customers", b =>
                {
                    b.Property<int>("CustomersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomersId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomersId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HotelManagePro.Features.Invoice.Models.Invoices", b =>
                {
                    b.Property<int>("InvoicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoicesId"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("TotalSum")
                        .HasColumnType("int");

                    b.HasKey("InvoicesId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("HotelManagePro.Features.Room.Models.Rooms", b =>
                {
                    b.Property<int>("RoomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomsId"));

                    b.Property<int>("BookingsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("RoomsId");

                    b.HasIndex("BookingsId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelManagePro.Features.Booking.Models.Bookings", b =>
                {
                    b.HasOne("HotelManagePro.Features.Customer.Models.Customers", null)
                        .WithMany("Bookings")
                        .HasForeignKey("CustomersId");

                    b.HasOne("HotelManagePro.Features.Invoice.Models.Invoices", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HotelManagePro.Features.Room.Models.Rooms", b =>
                {
                    b.HasOne("HotelManagePro.Features.Booking.Models.Bookings", "Booking")
                        .WithMany("Rooms")
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HotelManagePro.Features.Booking.Models.Bookings", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelManagePro.Features.Customer.Models.Customers", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
